engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  duplication:
    enabled: true
ratings:
  paths:
    - "**.php"
exclude_paths:
  - tests/
  - docs/
